### ISSUE TITLE
New sharing model does not have "image" nor "title" tag?

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#127]
Hi,
compared to last Facebook ANE, it seems new one does not have an "image" or "title" field.
Looks like a downgrade from previous sharing model.
Is it possible to publish an image on stream?
Thanks

**Comment by myflashlab** [comment]
That's Facebook's decision. but it seems like a good change. the image is automatically fetched via the ```contentUrl``` property. and instead of the old title thing, now we have a ```quote``` plus a lot of new cool properties. check out here http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/ShareContent.html

**Comment by PippoApps** [comment]
Ok so data is now retrieved from page stub then right?

**Comment by myflashlab** [comment]
> Ok so data is now retrieved from page stub then right?

Exactly.

**Comment by PippoApps** [comment]
Thank you. Implementing share with page stub.
