### ISSUE TITLE
iOS Simulator for Facebook review

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/facebook-ANE#145]
Hi,

I am using the Facebook ANE for Facebook login.  Works fine on a Facebook test app but as you know for a live build Facebook now want to approve certain permissions and in my case that includes user_friends which in turn means I have to provide them with a simulator build.

Now many of your ANE's, I believe, only work on real devices and sure enough, when I create a build on the simulator it appears to crash just after the launch screen.  Works fine on the real device. 

Is there any way to get round this? I need to be sure that when Facebook try and use the simulator itself it will work for them.

Have you had any apps that use your ANE's, walk through the minefield of Facebook approvals and come out the other side approved?

Thanks for your help

Stephen

**Comment by myflashlab** [comment]
We have built the [OverrideAir.isSupported](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairissupported) property especially for such reasons.

This way you can know that you are on a simulator and avoid initializing the ANEs. Instead of having a ```isSupported``` getter in every ANE, we are putting it only in one ANE. fair enough, right?

**Comment by LeapingSwan** [comment]
Thanks for the quick response.

If OverrideAir.isSupported <https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairissupported> is false presumably none of the ANE’s will be initiated right?

I do need at least the Facebook ANE to work as I need that since the whole purpose of the simulator build is so that Facebook can see the use case of user_friends live.

Otherwise I’m in a catch 22, unable to get a build that Facebook can test on iOS (they need both iOS and Android to test - I can do the .apk ok).

I have to admit that I find the whole process of simulator builds confusing, although I have done one in the past before using your ANE’s.  If any of you experts have been through the process and can give me a quick step by step guide, especially with regards the steps that I need to do it with your Facebook ANE working that would be great.  If you ever fancy building a tool that makes it really easy that would be great and I’m sure would be of great value to the whole community.

Thanks

Stephen

**Comment by myflashlab** [comment]
You’re right about the overrideAir. Please let us know if this might be helpful: https://stackoverflow.com/a/25507135

**Comment by myflashlab** [comment]
I think Facebook review team will be fine with the explanation like how it has been mentioned in the above link. However if really needed, we may consider building a simulator version of the ANE. But first let’s see what they would reply back to you.

**Comment by LeapingSwan** [comment]
Ok I’ll give that a go.  I have already asked them a question on this exact point but it might be more effective attached to a submission.

I’ll spend a couple of days getting the Android build ready so that I can submit that along with the explanation.  They do insist that you upload an iOS build before you can submit I think, so I may have to give them a broken one for iOS which might be a problem but we’ll see.

Even leaving aside the ANE issue it’s very complicated doing a simulator build from Animate CC, if you are not expert in ADT (and I’m not!) so a tool that made this more intuitive would be great for me and I would have thought others.

Thanks

Stephen

**Comment by myflashlab** [comment]
Yes, that would be good if they can go with the **onDevice** workaround. Nonetheless, We do have an iOS simulator version of both, the OverrideAIR and the main Facebook ANEs. And a few minutes ago I was talking with our iOS guy about this and he showed me how he can run the app on the iOS simulator with the Facebook and OverrideAIR ANE in it. So, In case the facebook review team didn't cooperate with you, no worries, you can get back to us and ask for the simulator supported version of the ANEs.

You may ask why we have not made these simulated ANEs public yet? Good question :) the reason is that we are doing a major upgrade on almost all of our ANEs. besides individual upgrades, there's a very general upgrade about how ANEs are connected to each other and how they interact with each other in different scenarios... Because of this reason, we are not able to release the completed ANEs just yet and we need a few more days to finish up all the remaining works. So, if the facebook review team is not convinced with your app usage, you need to wait a few days for us to release the newer version of ANEs including the simulated supported versions.

I'm closing the issue now but before doing that, let me explain on the following also:

> Even leaving aside the ANE issue it’s very complicated doing a simulator build from Animate CC, if you are not expert in ADT (and I’m not!) so a tool that made this more intuitive would be great for me and I would have thought others.

I hear you, yes, if you're not familiar with ADT, you will be loosing a lot of time when trying to build for iOS simulators especially when on AdobeAnimate. Maybe we would consider building such a tool in our [ANE LAB](https://github.com/myflashlab/ANE-LAB) but I'm not sure if many people would use it considering that [IntelliJ IDEA](https://www.jetbrains.com/idea/download/) is doing this job already very nicely.
