### ISSUE TITLE
Compiling on IOS error: ld: library not found for -lclang_rt.ios

### ISSUE THREAD

**Issue by xoopx** [myflashlab/facebook-ANE#147]
I get following error while compiling IOS version with new facebook.ane (26.09.2018)

ld: library not found for -lclang_rt.ios
ld: library not found for -lclang_rt.ios
Compilation failed while executing : ld64

AIR SDK 31 previous facebook.ane build doesn't has such problem.

**Comment by myflashlab** [comment]
Yes, that’s a bug in the AIR SDK. And this is how you should fix it: https://youtu.be/m4bwZRCvs2c

**Comment by xoopx** [comment]
Can you share this file as i dont have MAC

**Comment by myflashlab** [comment]
[libclang_rt.ios.a.zip](https://github.com/myflashlab/facebook-ANE/files/2423927/libclang_rt.ios.a.zip)

**Comment by xoopx** [comment]
Thanks, man!

**Comment by xoopx** [comment]
Yes, i have!

**Comment by myflashlab** [comment]
ok, this seems like a windows problem. please [vote this](https://tracker.adobe.com/#/view/AIR-4198557) up so Adobe can fix it as soon as possible. we will also look into more possible ways to see if we can find a workaround on Windows machines.

**Comment by myflashlab** [comment]
Tested with AIR 31 and still the same error as you mentioned above. This is not something in our control and Adobe should fix it. Until then, you should use a Mac to compile the .ipa file.

**Comment by myflashlab** [comment]
@LeapingSwan yes, copying ```-lclang_rt.ios``` must be done manually because sooner or later, Adobe will fix that bug and this is considered a workaround. However, about ```FBSDKMarketingKit.framework``` being copied, it should be working fine. we don't see a problem with that. could you provide more info on that? for example try hitting the **re-setup** button and watch if the frameworks are correctly copied? we don't seem to be able to duplicate this.

**Comment by LeapingSwan** [comment]
Ok, I think it was my fault.  I was just moving over from the demo version of the ANE's to the commercial ANELAB version having joined the club just yesterday.  So most of the files were already there and having updated the ANEs to the very latest I must not have re-run to install.  Works now.

Thanks

Stephen

**Comment by LeapingSwan** [comment]
Actually it's still not quite working right although I'm not sure it's the same issue:

Basically with the new Facebook ANE I am getting 

	1046: Type was not found or was not a compile-time constant: AccessToken.
	1046: Type was not found or was not a compile-time constant: FacebookEvents.
	1046: Type was not found or was not a compile-time constant: FacebookEvents.

My code is:	

import com.myflashlab.air.extensions.fb.*;
import flash.events.InvokeEvent;

Facebook.init(FACEBOOK_APP_ID);
Facebook.listener.addEventListener(FacebookEvents.INIT, onAneInit);
Facebook.listener.addEventListener(FacebookEvents.INVOKE, onAneInvoke);

public static function loginCallback(bIsCanceled:Boolean, eError:Error, accessToken:AccessToken, recentlyDeclined:Array, recentlyGranted:Array):void
{
       // More code here
 }

public static function onAneInvoke(e:FacebookEvents):void
{
	trace("INVOKE");
	trace("onAneInvoke: " + decodeURIComponent(e.deeplink));
}

public static function onAneInit(e:FacebookEvents):void
{
	trace("onAneInit ");
	trace("FBtoken " + FBtoken);
	trace("Facebook " + Facebook);
	trace("Facebook.auth " + Facebook.auth.toString());
	trace("Facebook.auth.currentAccessToken " + Facebook.auth.currentAccessToken);
  
       // More code

}

All this code worked fine before the Facebook ANE update.

Thanks

Stephen

**Comment by myflashlab** [comment]
These errors usually happen when you have not implemented the ANE into your app correctly.

Notice that when you are using ANELAB, name of ANE files will be changed. So your IDE might loose it. Depending on your IDE, you may need to make sure it is able to read the ANE files.

One of the reasons that we suggest users to switch to the IntelliJ is that in this IDE, you can set a folder as the base location of your current project’s ANEs. Adding, removing or renaming the ANEs wouldn’t need any manual correction and the IDE will find and embed them automatically. But other IDEs, you should be careful with them. I hope this information is helpful to you. 

Please consider opening new tickets for other issues rather than the original title of the thread. Thanks.

**Comment by LeapingSwan** [comment]
Sorry thought it might have been a related issue.  Moving to a new thread

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
