### ISSUE TITLE
IOS build is not compiling

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/facebook-ANE#26]
I have followed the following steps to build the IOS app with this facebook ane

1, I have added the required ane to flash,
2. AIR SDK version is 19.
3. Copied the facebook framework to AIR SDK
4. Modified the Manifest.xml

But it not compiling the IOS version, I have tried the android and that is working fine, Let me know what is wrong here, so that i can correct that and compile the IOS version

**Comment by myflashlab** [comment]
What is your IDE?

On Thursday, January 21, 2016, navdeepyadav <notifications@github.com>
wrote:

> I have followed the following steps to build the IOS app with this
> facebook ane
>
> 1, I have added the required ane to flash,
> 2 AIR SDK version is 19
> 3 Copied the facebook framework to AIR SDK
> 4 Modified the Manifestxml
>
> But it not compiling the IOS version, I have tried the android and that is
> working fine, Let me know what is wrong here, so that i can correct that
> and compile the IOS version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/26>.
>


-- 
Sent from iPhone

**Comment by navdeepyadav** [comment]
I am using Flash professional CS6

**Comment by myflashlab** [comment]
And what error you are receiving?

On Thursday, January 21, 2016, navdeepyadav <notifications@github.com>
wrote:

> I am using Flash professional CS6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/26#issuecomment-173474809>
> .
>


-- 
Sent from iPhone

**Comment by navdeepyadav** [comment]
I am not receiving any error yet, its compiling endlessly since last 50-60 mins
![screenshot 2016-01-21 12 39 41](https://cloud.githubusercontent.com/assets/16606299/12473867/1b4aa0ca-c03c-11e5-97a4-21e7a68498d2.png)

**Comment by navdeepyadav** [comment]
Is it going to be solved today?

**Comment by navdeepyadav** [comment]
Dear Support Admin, I am expecting solution for this issue with the facebook Ane, Can you please look into this

**Comment by myflashlab** [comment]
we are issuing an update on all our extensions due to a recent bug in xcode
7.2 and AirSDK 20 which might fix your problem too. so, hold on for the
release news today on our facebook/twitter (
https://www.facebook.com/myflashlab/) (https://twitter.com/myflashlab)
pages. you may also learn more about the recent problem here
https://forums.adobe.com/thread/2055508
https://forums.adobe.com/message/8294948

considering that you are using AirSDK 19, this release may not help you,
but it's a good shot anyhow.

besides, please watch this playlist. you may find something useful on them:
https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by navdeepyadav** [comment]
I am using the  AIR SDK after i post here few days, They mentioned that AIR SDk 20 is not working for IOS build, I do not have any issue in updating my SDK version

**Comment by myflashlab** [comment]
please continue on here: https://github.com/myflashlab/facebook-ANE/issues/27
