### ISSUE TITLE
CameraRoll crash silently after using ANE

### ISSUE THREAD

**Issue by msmpro** [myflashlab/facebook-ANE#30]
Hi,
I'm using AIR 19 with purchased version of ANE. 
When I login with ANE or share content and after this I launch CameraRoll, and I select one picture, the CameraRoll class stop responding (crash silently and return to the app to continue working. No error event dispatched). If I launch CameraRoll one more time I have an error message, because one instance of CameraRoll continue open.
If I launch the CameraRoll befor login with ANE, everything works correctly.

Any idea about this?
Thanks in advance.

**Comment by myflashlab** [comment]
on what platform does this happen? Android or iOS? and what do you mean by CameraRoll exactly? another extension?

**Comment by msmpro** [comment]
Sorry, on Android platform.
I'm using CameraRoll from flex/Air sdk not another extension.

**Comment by msmpro** [comment]
Hi, the code:
`import flash.media.CameraRoll;
...
FB.getInstance(FB_APP_ID_NUMBER);
FB.logManager.addEventListener(FBEvent.LOGIN_DONE, fbGetPermissionPublishSuccess);
FB.logManager.addEventListener(FBEvent.LOGIN_CANCELED, fbGetPermissionCanceled);
FB.logManager.addEventListener(FBEvent.LOGIN_ERROR, fbGetPermissionError);
FB.logManager.requestPermission(LogManager.WITH_PUBLISH_PERMISSIONS, Permissions.publish_actions);
...
private function fbGetPermissionPublishSuccess(event:FBEvent):void {
if (CameraRoll.supportsBrowseForImage) {
		camera = new CameraRoll();
		camera.addEventListener(MediaEvent.SELECT, mediaEventComplete);
		camera.addEventListener(Event.CANCEL, browseCancelled);
		camera.addEventListener(ErrorEvent.ERROR, mediaErrorHandler);
		// Open up the camera roll
		camera.browseForImage();
	}
}
`
No one of the handlers (mediaEventComplete, browseCancelled, mediaErrorHandler) is launched if I use the ANE before the CameraRoll.

Maybe some events is canceled in the code of ANE?

Thanks in advance.

**Comment by myflashlab** [comment]
yes, we also tested and you're right. the cameraRoll silently will crash! and its listeners won't dispatch. We also tested on iOS to see if that is the case on iOS but it worked just fine.

We tried to look for any error messages in ADB log but there was no error messages there either! How can these two completely different libraries be related to each other is surprising but our wild guess is that maybe it's because we had to override some Adobe classes inside the FB extension to be able to read the Facebook callbacks. without that, the extension couldn't work. This is just a wild guess and maybe it's wrong because we did the very same thing on the iOS side and it's working fine!

anyway, considering that we have no clue how Adobe's cameraRoll works, I think you should ask about this in Adobe's forums for more information from their side.

As an alternative, you could try our file-chooser ANE https://github.com/myflashlab/fileChooser-ANE the good thing about that is that it will resize the returned image to you so you don't have to load a huge image into your Air app.

Please update us about how you going with this and we'll try to help as much as possible as this has been a very interesting question/issue.

**Comment by msmpro** [comment]
Hi,
just one question, if you test the code with AIR 20 on Android the CameraRoll works after calling the ANE?

I will post a question about this in Adobe's forum later (I hope they help me with third party library...).
Maybe the paid way (your file-chooser ANE) is an option... I tested it yesterday in a new project and I only get the popup showing it's a demo, but nothing more is happening. I will test it again later.

Thanks.

**Comment by myflashlab** [comment]
> if you test the code with AIR 20 on Android

Yes, we tested with Air20. on iOS cameraRoll listeners worked but not on Android.

If you faced any question about fileChooser-ANE feel free to ask in its issues page.

**Comment by msmpro** [comment]
Nothing about this bug on Adobe forums.
The alternatives is to use your file-chooser ANE or other facebook ANE.

Thank you.

**Comment by myflashlab** [comment]
OK, thanks. I will write this down on the board anyway so we can do further investigations later. Our wild guess is that the official CameraRoll will face similar problems with other ANEs which may require native java overriding of Adobe's classes. so, yes, your best shot currently is to use our file chooser ANE. we might update this ticket in future if we could hear some news from Adobe in this regard. I would appreciate if you can post a link to the question you posted on Adobe forums here just for future references. Thanks.

**Comment by msmpro** [comment]
Here are the links:
[Adobe bugbase](https://bugbase.adobe.com/index.cfm?event=bug&id=4112483)
[Adobe forum](https://forums.adobe.com/message/8449973#8449973)

Thank you one more time!
