### ISSUE TITLE
Minumum version of common dependencies

### ISSUE THREAD

**Issue by msmpro** [myflashlab/facebook-ANE#32]
Hi,

Packaging with common dependencies ANE add 8MB to the APK release. I thinks it's too much...
 it's possible to have a minumum version of common dependencies ANE? it's depend on functionality used from facebook ANE?

I'm packaging on Android and AIR 19 (on IOS, if I'm right, it's not necessary to include common depencies ANE to release).

Thanks.

**Comment by myflashlab** [comment]
Yes, We are of this problem and we are actually preparing for a whole new approach to fix the common dependencies large file sizes issue. 

You're right, it's not needed on the iOS side but you don't have to remove it when packaging .ipa because it won't add any extra bytes to your project maybe just a few KB but nothing considerable.

**Comment by myflashlab** [comment]
Good timing right? :) Please [read here](https://github.com/myflashlab/facebook-ANE#requirements) and you will know which common-dependency ANEs you need to add to your project.

we have now separated the dependencies into multiple ANEs and each ANE includes only the necessary shared libraries.
