### ISSUE TITLE
Facebook login screen language does not change when selecting a different language

### ISSUE THREAD

**Issue by GordonJames** [myflashlab/facebook-ANE#42]
The Facebook login screen has many language links at the bottom and when I click any of them the page refreshes but the language is still the same (English in my case). I tried on many Android devices with the same results.

**Comment by GordonJames** [comment]
It appears the Facebook Login screen language is set equal to the device preferred language and the Facebook permission confirmation screen language is set equal to the Facebook user's locale settings. This behavior is fine and although the language links on the Facebook login screen don't work, I can live with it.

**Comment by myflashlab** [comment]
Would you please update to V4.11.0 and tell us if the language picker is now fixed?

**Comment by GordonJames** [comment]
Latest Version still does not work! Same problem.

**Comment by myflashlab** [comment]
Considering that the ANE is switching to the Facebook library, I'm not sure if it is something we can fix because we have already inserted all the required FB resources. we'll try to keep an eye on Facebook SDK changelogs and we'll update the ANE as soon as something changed in that regard. Thanks for reporting this anyway.
