### ISSUE TITLE
Detecting using ANE if user is logged on Facebook in Safari..

### ISSUE THREAD

**Issue by ionutmihaila** [myflashlab/facebook-ANE#48]
Hi guys,

One question please related to Like button on iOS:

Is there any way to detect, using your ANE, if the user is logged in on Facebook in Safari? I'm asking because if he's going to push the Like button from my app and he's not logged in in Safari, he will have to log in before taking any like action, which in my opinion it's a bad experience, so I would like to use the Like button only for users that are already logged in on Facebook.

Thank you!

**Comment by myflashlab** [comment]
[This solution](https://github.com/myflashlab/facebook-ANE/issues/50) can work for this one also?

**Comment by ionutmihaila** [comment]
Correct, tested and works fine.. Many thanks! ;)

**Comment by myflashlab** [comment]
I don't think you can find out if you are logged in Safari or not. The
reason is clear, the safari app itself can know if it's logged in or not,
not anyone else!

However, if you don't wish your users to hit the "like" button unless they
are logged in safari, maybe you can check users logged in status within
your app first and hide the "like" button if they are not logged in. This
solution may work for you because since Facebook SDK 4.x.x which it is
using safari webview instead of opening the FB app, you can be conside your
user logged in safari if she's already logged in your app. Because she
couldn't have logged in to your app if she hadn't logged into safari before
that! Am I making sense? :) I somehow got confused by my own words :)) but
I think you got the idea.

On Sunday, July 10, 2016, ionutmihaila <notifications@github.com> wrote:

> Reopened #48 <https://github.com/myflashlab/facebook-ANE/issues/48>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/48#event-717899257>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnVFGq7U78Jx13NhCYl0X98TubnyJtYks5qUDFCgaJpZM4JE3Tb>
> .
>


-- 
Sent from iPhone

**Comment by ionutmihaila** [comment]
I understand, it's ok then, I'll hide the Like button if people are not logged in my app.. Thank you!
