### ISSUE TITLE
FB.getInstace() cancells InvokeEvent on IOS

### ISSUE THREAD

**Issue by ionutmihaila** [myflashlab/facebook-ANE#49]
Hi guys,

Found an ugly one, please help :| 

There is a known AIR issue on IOS: the InvokeEvent it's called twice when you enter the app, at first call the InvokeEvent.arguments[0] is undefined, but at second call the InvokeEvent.arguments[0] contains correct URL, which it's fine.

Well, it looks like after FB.getInstance("app_id") from your ANE it's called, the second call from InvokeEvents doesn't exist, which means the InvokeEvent.arguments[0](the URL) can't be collected. Steps to reproduce:
1. Enter app and launch FB.getInstance("app_id");
2. Exit app
3. Enter app via a shortURL (you'll see InvokeEvent.arguments[0] is missing now)

Is there any workaround to fix this please?
Something to cancel the FB.getInstance() at launch or anything else? (tried with FB.dispose() but doesn't work)

Many thanks!
Ionut

**Comment by myflashlab** [comment]
We'll investigate this a.s.a.p and update you. Thanks.

**Comment by ionutmihaila** [comment]
Hi guys,

Any update on this please? At least an estimated date when you think it will be fixed?

Many thanks!

**Comment by ionutmihaila** [comment]
Guys, any update on this please? It's been more than 3 weeks since this was raised :|

**Comment by myflashlab** [comment]
@ionutmihaila We are deeply sorry for the LATE reply. you know, the Firebase project we have been working on for the past month has been made us work day and night with full concentration. Hopefully the first phase of that project is now completed...

Anyway, I just checked your question with the iOS team in great details and here are the results:

Unfortunately you are right. This is a bug and we can clearly see it but the hard part is that the bug is not on the ANE side! It's on the Air SDK part. Let me explain it though.

The original ```InvokeEvent.INVOKE``` listener seems to be too old and Adobe needs to update that soon or later because we have faced MANY troubles with it. Just to name a few:

1) The [spotlight ANE](http://www.myflashlabs.com/product/ios9-spotlight-air-native-extension/) opens apps after user hits a search result and when the Air app opens, you are expecting the incoming variables to be collected by the  ```InvokeEvent.INVOKE``` listener. But that does not happen! In order to make the spotlight ANE work fine, we finally decided to make some nasty hacks to collect the incoming variables.

2) The new FCM SDK (the one replacing GCM by the new Firebase SDK) is also sending variables to the app when users click on the notifications. Unfortunately that is also not working at the moment. However the GCM ANE is collecting the variables correctly.

3) The dynamic links in the Firebase SDK is also using a similar thing and we are currently scratching our heads to find a solution which seems not to be available at the moment.

And now, you have detected this problem on the current Facebook ANE.

So, what I think we should do is for us to open a new bug report in Adobe and we will explain the problem in details so they can duplicate the problem and find a solution for this because this feature is being used in many new iOS SDKs and I'm sure Adobe will find a solution for it.

Thanks for your report.

**Comment by ionutmihaila** [comment]
I understand.. appreciate the effort you put into checking this.. Please let me know once the bug is raised to Adobe, so I can chase it.. Many thanks!

**Comment by lucien144** [comment]
Hi @myflashlab ,
any news on this? Any possible workaround?

Thanks.

**Comment by lucien144** [comment]
Following up: What's the option if we want to keep continue using this ANE but also need deeplinking to our app (especially from share links). You said that the Dynamic links Firebase ANE does not work either, so what's the option?

Thanks.

**Comment by myflashlab** [comment]
Dynamic-links does work now when using AIR SDK 24. However, as far as the FB, we are working on a new version to see what are our options.

**Comment by lucien144** [comment]
@myflashlab Thanks for reply. One more question - does dynamic-links works together with Facebook ANE?

Thanks.

**Comment by myflashlab** [comment]
It does but you need to make sure you are using the latest version of them both because we have recently updated them all to make sure they are not overriding each other similar methods. If you faced a problem while using the Dynamic-Links and Facebook, let us know.

**Comment by vietpv** [comment]
@myflashlab  : how to get Dynamic-Links from facebook-ane, thanks

**Comment by myflashlab** [comment]
We are strongly suggesting [Firebase Dynamic links](https://github.com/myflashlab/Firebase-ANE/wiki/I.-Dynamic-Links) for apps. They work awesome cross-platforms.

**Comment by vietpv** [comment]
@myflashlab  : if u can, plz add new function get Dynamic-Links in new vesion facebook-ane, thanks

**Comment by myflashlab** [comment]
We will try to consider this for the next releases. sure.

**Comment by myflashlab** [comment]
With our latest release, we have added GameRequests and one thing to be fixed when adding this feature is how deeplinks are handeled with the Facebook ANE. we have now added the requred deeplinking feature with the new ```FacebookEvents.INVOKE``` listener. please try the new ANE and see how it goes.

> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
