### ISSUE TITLE
Problem with login: invalid hash key

### ISSUE THREAD

**Issue by DFABRIK** [myflashlab/facebook-ANE#52]
I have problem with hash key.
![feler](https://cloud.githubusercontent.com/assets/18464109/17040697/99ac9eb0-4fa1-11e6-9887-7f1a456128c6.jpg)
Even when I add this key from alert it possible to login only once, After that I get error with new hash key. What's the problem?

**Comment by myflashlab** [comment]
Invalid key hash, simply means what it says! Your key hash is invalid. You need to make sure you are correctly adding your key hash to your Facebook panel. 

Hint: if you are running on FlashBuilder, you should be careful when running your app in debug mode because This IDE automatically adds "debug" to your app package name. You need to make sure the key hash you copied is the correct one.

**Comment by DFABRIK** [comment]
Yes, obviously it use one hash key for debug one hash key for release. Seems OK now.
