### ISSUE TITLE
iOS Publish

### ISSUE THREAD

**Issue by gadyosef** [myflashlab/facebook-ANE#62]
Hi guys, 
On iOS, after trying to upload an IPA, it's being rejected with this message:
(Already checked all the recommended things like certificate etc.)

"ERROR ITMS-90035: "Invalid Signature. A sealed resource is missing or invalid. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

** EDIT ** 
After many tries, I reverted my Air SDK version to 19 (Since my last build worked and I changed the SDK version to implement your Ane), uploaded to Apple - was uploaded and no error.
(But I guess nothing will work if I use this version since the sdk version is under the required version...)

Any leads from That?

**Comment by myflashlab** [comment]
Well, you should try AIR SDK 23. However, this problem is not related to the ANE to begin with, so I'm closing the issue. Maybe trying to post the question on stackoverflow or Starling forums. We do understand the frustration of uploading .ipa files to iTunes :) and we hope you can find a solution to that soon. In this repository however, we are trying to consecrate on questions related to the ANEs directly. Thanks.
