### ISSUE TITLE
Official facebook client is interfering to login

### ISSUE THREAD

**Issue by MyMyGames** [myflashlab/facebook-ANE#77]
Сannot login using facebook. 
When trying to login it shows error "invalid hash key". 
and shows wrong hash key in that error message.   
app is able to login only through browser (web login) if official facebook client is removed from device completely.

Your Demo.apk [https://github.com/myflashlab/facebook-ANE/tree/master/FD/dist] (with FB ANE v4.11.00) work fine.
Can you create a new version of the application with ANE v.4.17.00?
I want to try to understand where problem is.

**Comment by myflashlab** [comment]
Please try the new released version (make sure to read the changelog carefully) and see how it works. Make sure you are using a correct hashKey. Note that in FlashBuilder, your debug/release builds might have a different hashkeys because FB changes app name automatically. This has been described in our videos: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by myflashlab** [comment]
Please let us know if this problem is fixed?
