### ISSUE TITLE
Issue in the ANE when user clears the application data and cache.

### ISSUE THREAD

**Issue by babakasol** [myflashlab/facebook-ANE#79]
Facing an issue with this ANE while logging in. Explaining the scenario in steps:
1. For the first time if i log in using this ane it works fine and facebook provides the authentication.
2. Now if i clear the application data and cache and try logging in again with facebook it dosent logs me in, the white screen appears and it disappears after 3 4 seconds.
3. Now the same thing is happening with the demo.apk that has been provided by you.
4 The problem is that the app get registered with facebook, and if i remove the app from facebook app setting page and then try logging in it will work fine but only for the first time, next time if i uninstall the app and reinstall it and again try login i face the same issue.

 Please try this with your demo apk it will be clear to you.

**Comment by anupamverma170191** [comment]
Yes, this issue is there with the demo.apk as well.
Even am facing the same problem with this ANE. I am able to login for the first time but when i uninstall the application and reinstall it something is wrong with the "FB.auth.requestPermission" because i get the webview screen but as soon as it starts loading it crashes.
Since facebook has already granted the permission for the application then it should not ask for it again as the application is already added in the facebook applicatins tab.

**Comment by myflashlab** [comment]
This is interesting. We are actually working on a new version of the ANE and we'll make sure to check this issue also.

**Comment by anupamverma170191** [comment]
Mean while is there any work around for this issue and by when will this new version of ANE be available?

**Comment by anupamverma170191** [comment]
Is there any update on the issue? Did you find the issue in the demo.apk file. Kindly reply if there is any solution.

**Comment by myflashlab** [comment]
We are working on a new version of the ANE. It should be released soon... please hang on, we're working on it.

**Comment by myflashlab** [comment]
Please try [this demo ANE](https://drive.google.com/file/d/0B7eHG2CEml2TbFAzLThlcDdObW8/view?usp=sharing) while you are changing your manifest to this:

change **[FB_APP_ID]** to your Facebook App ID
```xml
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ [FB_APP_ID]"/>

<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="My App Name" />
		<activity android:name="com.doitflash.facebook.access.MyLogin" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@style/Theme.Transparent" />
		
		<activity
			android:name="com.facebook.CustomTabActivity"
			android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="fb[FB_APP_ID]" />
			</intent-filter>
		</activity>
```
With this version, everything seems fine on our side. that would be great if you can also confirm it while we are finishing the iOS side of the ANE and other optimizations.

**Comment by anupamverma170191** [comment]
Thanks for the reply and the demo version of the ane. Well i have included the demo ane and when am making a release build to check the issue its throwing me the following error: 

aapt tool failed:C:\Users\Anupam\AppData\Local\Temp\58dc2027-c4f6-401d-9b5e-cfad3af4d8d4\com.facebook-res\values\values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.



C:\Users\Anupam\AppData\Local\Temp\58dc2027-c4f6-401d-9b5e-cfad3af4d8d4\com.facebook-res\values\values.xml:136: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.

So tell me if am missing anything at my end. Or how can it be resolved.

**Comment by myflashlab** [comment]
You need to use the new androidSupport.ane file I linked above.

**Comment by anupamverma170191** [comment]
Okay i have added the new androidSupport.ane and updated the AIR SDK 25 still facing the same issue after uninstalling and then reinstalling the app. I get a white screen which is webview and a preloader but after 2-3 secs it disappers and nothing happens. For your refrence and sharing the xml enteries am using

<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="4383845331XXXX"/>

<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="My App Name" />
<activity android:name="com.doitflash.facebook.access.MyLogin" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@style/Theme.Transparent" />

<activity
	android:name="com.facebook.CustomTabActivity"
	android:exported="true">
	<intent-filter>
		<action android:name="android.intent.action.VIEW" />
		<category android:name="android.intent.category.DEFAULT" />
		<category android:name="android.intent.category.BROWSABLE" />
		<data android:scheme="fb43838453317XXXX" />
	</intent-filter>
</activity>

Note:-XXXX  is the FB appId.
If anything is missing here let me know.

**Comment by anupamverma170191** [comment]
Did you find any issue with these entries?

**Comment by myflashlab** [comment]
change ```<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="/43838453XXXXXXX"/>``` to:

```xml
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="/ 43838453XXXXXXX"/>
```

Notice the space after the ```\```

**Comment by anupamverma170191** [comment]
Made the changes suggested by you but still the problem is same. Am telling you the exact scenario where am facing the issue so that it may help you to understand where the problem is:
>I am developing a application and included the Facebook.ane for logging in through facebook.
>Once i log-in using for the first time my Application gets registered to facebook i.e. in Facebook>Settings>Apps> i find my application.
>Now if i uninstall the application or clear the cache and data and reinstall the app then i am facing this problem. I am not able to log in using facebook. White screen appears and its not able to load the webview.
But if i go to Facebook>Settings>Apps> and remove my already registered app from facebook it starts working.

I am a club member and have purchased this ane but its with my different account. So if you want i can message you from that account as well. Please see where things are going wrong. Thanks fro your quick response.

**Comment by myflashlab** [comment]
Ok, There should be something missing now because we can't duplicate this... hmm, can you make a video cast of how this is happening? so we can see the steps in action...? and by the way, we have released V4.22.1 with some other improvements. That would help us a lot if you can run the newer ANE and se how it goes.

**NOTICE** The club package should be updated by tomorrow this time though. so, you may use the demo ANE for now.

**Comment by anupamverma170191** [comment]
Okay i will try to provide you with the video cast of the issue but for now i think there is something wrong with the XML entries i guess. I have made the changes in the xml as mentioned but getting this error will building::-
```
aapt tool failed:Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
C:\Users\Anupam\AppData\Local\Temp\7227c7d0-71b4-4619-b889-42fe3817b871\AndroidManifest.xml:177: Tag <activity> missing required attribute name.
```

**Comment by anupamverma170191** [comment]
Please can you go through this error and tell me where am going wrong.

**Comment by anupamverma170191** [comment]
I am sharing a video link so that you can see how its happening. I installed a fresh app and logged in using facebook. I was able to login without any issue. After that i went to settings and removed cache and data of the app and then again tried logging in and got the white screen and nothing happen after that. We require this feature in our application so please how it can be resolved. 
Here  is the link of google drive: https://drive.google.com/file/d/0B8kX2_4Wjxm-MWUwUGNxSzE4dTQ/view?usp=sharing

**Comment by anupamverma170191** [comment]
The issue is resolved. Thanks for your concern and help.
 There was something wrong with the HASH Key we were using.. :)
