### ISSUE TITLE
IOS- Login process always returning onLogin_canceled

### ISSUE THREAD

**Issue by babilux** [myflashlab/facebook-ANE#90]
Hello myflashlabs team!

I'm testing your demo version and thanks to your tutorial all the steps to setup the ANE and facebook app creation is well done. My tests on the " share to friend" ,"like" is working like a charms via the safariview controller.
Well i would buy it if only the login /logout process  was working and returning the token and so on .. which I don't know why , has not  even happened one time after tryed  tone of time and checked  the manifest , fb app side, and the demo code you provide.

When I press the login button it well opens the safariview controller, where i can see  the facebook auth page related to my app, and when pressing "confirmation" it closes SWcontroller and nothing else happen expect " login cancelled " in the console.

Any idea how i can fix this? May i'm forgetting something?

Thanks by advance for your help!

**Comment by seilz2k5** [comment]
Same over here. Although i'm running the commercial version. Works on Android, but not on iOS. 
Also the safari browser is always opened, even if the facebook app is installed. 

I double and tripple checked on the docu, but i'm always getting the login cancelled event when returning from safari to my app after hitting the connect button.

**Comment by seilz2k5** [comment]
Additional note on that issue:
I suspect this issue being related to the Custom URL Schemes, because i think the browser would open up my app after i tapped the connect/ok button.
This then should send a token to the app via the InvokeEvent on the native application singleton.

I see that there is no uri or additional information available in the arguments array of this event (array of length 0).
Hope that helps! Maybe this is AIR SDK related?

**Comment by myflashlab** [comment]
[facebook.ane.zip](https://github.com/myflashlab/facebook-ANE/files/1236166/facebook.ane.zip)

Awesome finding guys. This problem has been caused by our recent changes with the OverrideAir.ane we have updated the ANE to be able to read the incoming fb link from the customtab window. while we are putting everything together, please test the attached ANE and confirm if it also works on your side?

**Comment by myflashlab** [comment]
V4.22.2 is now released and this problem is fixed. if you experienced anything else, please let us know. Thanks.

**Comment by seilz2k5** [comment]
Works on my side! (Both, the ane you posted and the updated commercial one). 
Cheers
